### ISSUE TITLE
Error by retrieving image of kiwix/kiwix-serve

### ISSUE THREAD

**Issue by kelson42** [offspot/docker-export#2]
```
$ docker-export kiwix/kiwix-serve kiwix-serve.image
INFO:Starting index.docker.io/kiwix/kiwix-serve:latest (linux/arm/v7) export into /home/kelson/code/docker-export/kiwix-serve.image/index.docker.io_kiwix_kiwix-serve.tar
INFO:Exporting 7 layers (25.87 MiB) into /tmp/index.docker.io_kiwix_kiwix-servehvy_rw7t.tmp
INFO:> [6366ba92f08e] Downloading 2.3 MiB…
[Elapsed Time: 0:00:00]   2.3 MiB|####################################################################################################|176.2 MiB/s (Time:  0:00:00)
INFO:> [6366ba92f08e] Extracting...
INFO:> [6366ba92f08e] Adding metadata…
INFO:> [bd697ce7ae80] Downloading 34.26 KiB…
[Elapsed Time: 0:00:00]  34.3 KiB|####################################################################################################| 33.3 MiB/s (Time:  0:00:00)
INFO:> [bd697ce7ae80] Extracting...
INFO:> [bd697ce7ae80] Adding metadata…
INFO:> [21ad945d3e50] Downloading 147 bytes…
[Elapsed Time: 0:00:00] 147.0 B|######################################################################################################|196.9 KiB/s (Time:  0:00:00)
INFO:> [21ad945d3e50] Extracting...
INFO:> [21ad945d3e50] Adding metadata…
INFO:> [1b82e75e5b92] Downloading 150 bytes…
[Elapsed Time: 0:00:00] 150.0 B|######################################################################################################|125.2 KiB/s (Time:  0:00:00)
INFO:> [1b82e75e5b92] Extracting...
INFO:> [1b82e75e5b92] Adding metadata…
INFO:> [daee9ad170fd] Downloading 23.54 MiB…
[Elapsed Time: 0:00:00]  23.5 MiB|####################################################################################################| 45.8 MiB/s (Time:  0:00:00)
INFO:> [daee9ad170fd] Extracting...
INFO:> [daee9ad170fd] Adding metadata…
INFO:> [c784ac0d1cc4] Downloading 100 bytes…
[Elapsed Time: 0:00:00] 100.0 B|######################################################################################################|140.3 KiB/s (Time:  0:00:00)
INFO:> [c784ac0d1cc4] Extracting...
INFO:> [c784ac0d1cc4] Adding metadata…
INFO:> [2b134fb39279] Downloading 435 bytes…
[Elapsed Time: 0:00:00] 435.0 B|######################################################################################################|520.6 KiB/s (Time:  0:00:00)
INFO:> [2b134fb39279] Extracting...
INFO:> [2b134fb39279] Adding metadata…
INFO:Adding Image metadata…
INFO:Creating archive at /home/kelson/code/docker-export/kiwix-serve.image/index.docker.io_kiwix_kiwix-serve.tar
ERROR:FAILED. An error occurred: [Errno 2] No such file or directory: '/home/kelson/code/docker-export/kiwix-serve.image/index.docker.io_kiwix_kiwix-serve.tar'
ERROR:[Errno 2] No such file or directory: '/home/kelson/code/docker-export/kiwix-serve.image/index.docker.io_kiwix_kiwix-serve.tar'
Traceback (most recent call last):
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 730, in main
    export(image=image, platform=platform, to=dest, build_dir=build_dir)
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 647, in export
    export_layers(
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 613, in export_layers
    bundle_image(
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 551, in bundle_image
    with tarfile.open(target, "w") as tar:
  File "/usr/lib/python3.10/tarfile.py", line 1662, in open
    return cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.10/tarfile.py", line 1672, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.10/tarfile.py", line 1484, in __init__
    fileobj = bltn_open(name, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kelson/code/docker-export/kiwix-serve.image/index.docker.io_kiwix_kiwix-serve.tar'
```

**Comment by kelson42** [comment]
Looks better if I export to a filename ending with `.tar`
```
$ docker-export kiwix/kiwix-serve kiwix-serve.image.tar
INFO:Starting index.docker.io/kiwix/kiwix-serve:latest (linux/arm/v7) export into /home/kelson/code/docker-export/kiwix-serve.image.tar
INFO:Exporting 7 layers (25.87 MiB) into /tmp/kiwix-serve.imagegnt3wz_0.tmp
INFO:> [6366ba92f08e] Downloading 2.3 MiB…
[Elapsed Time: 0:00:00]   2.3 MiB|####################################################################################################|113.6 MiB/s (Time:  0:00:00)
INFO:> [6366ba92f08e] Extracting...
INFO:> [6366ba92f08e] Adding metadata…
INFO:> [bd697ce7ae80] Downloading 34.26 KiB…
[Elapsed Time: 0:00:00]  34.3 KiB|####################################################################################################| 66.4 MiB/s (Time:  0:00:00)
INFO:> [bd697ce7ae80] Extracting...
INFO:> [bd697ce7ae80] Adding metadata…
INFO:> [21ad945d3e50] Downloading 147 bytes…
[Elapsed Time: 0:00:00] 147.0 B|######################################################################################################|237.7 KiB/s (Time:  0:00:00)
INFO:> [21ad945d3e50] Extracting...
INFO:> [21ad945d3e50] Adding metadata…
INFO:> [1b82e75e5b92] Downloading 150 bytes…
[Elapsed Time: 0:00:00] 150.0 B|######################################################################################################|246.2 KiB/s (Time:  0:00:00)
INFO:> [1b82e75e5b92] Extracting...
INFO:> [1b82e75e5b92] Adding metadata…
INFO:> [daee9ad170fd] Downloading 23.54 MiB…
[Elapsed Time: 0:00:00]  23.5 MiB|####################################################################################################| 44.3 MiB/s (Time:  0:00:00)
INFO:> [daee9ad170fd] Extracting...
INFO:> [daee9ad170fd] Adding metadata…
INFO:> [c784ac0d1cc4] Downloading 100 bytes…
[Elapsed Time: 0:00:00] 100.0 B|######################################################################################################| 98.3 KiB/s (Time:  0:00:00)
INFO:> [c784ac0d1cc4] Extracting...
INFO:> [c784ac0d1cc4] Adding metadata…
INFO:> [2b134fb39279] Downloading 435 bytes…
[Elapsed Time: 0:00:00] 435.0 B|######################################################################################################|  1.3 MiB/s (Time:  0:00:00)
INFO:> [2b134fb39279] Extracting...
INFO:> [2b134fb39279] Adding metadata…
INFO:Adding Image metadata…
INFO:Creating archive at /home/kelson/code/docker-export/kiwix-serve.image.tar
INFO:Removing temp image dir /tmp/kiwix-serve.imagegnt3wz_0.tmp
INFO:Docker image exported: /home/kelson/code/docker-export/kiwix-serve.image.tar
```
