### ISSUE TITLE
Unable to export openzim/gutenberg (v1 single platform and mismatches)

### ISSUE THREAD

**Issue by kelson42** [offspot/docker-export#3]
```
$ docker-export openzim/gutenberg gutenberg.image.tar
INFO:Starting index.docker.io/openzim/gutenberg:latest (linux/arm/v7) export into /home/kelson/code/docker-export/gutenberg.image.tar
ERROR:FAILED. An error occurred: index.docker.io/openzim/gutenberg:latest is v1 single platform and mismatches
ERROR:index.docker.io/openzim/gutenberg:latest is v1 single platform and mismatches
Traceback (most recent call last):
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 730, in main
    export(image=image, platform=platform, to=dest, build_dir=build_dir)
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 641, in export
    manifest = get_layers_manifest(image=image, platform=platform, auth=auth)
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 369, in get_layers_manifest
    return get_layers_from_v1_manifest(
  File "/home/kelson/.local/lib/python3.10/site-packages/docker_export/__init__.py", line 339, in get_layers_from_v1_manifest
    raise ValueError(f"{image} is v1 single platform and mismatches")
ValueError: index.docker.io/openzim/gutenberg:latest is v1 single platform and mismatches
```

**Comment by rgaudin** [comment]
As explained, I believe properly in the error message, gutenberg image has a single platform that doesn't match  your request (armv7).
